version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: pulsar_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=pulsar_user
      - POSTGRES_PASSWORD=pulsar_password
      - POSTGRES_DB=pulsar_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pulsar_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pulsar_user -d pulsar_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: pulsar_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - pulsar_net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    container_name: pulsar_backend
    image: golang:1.24-alpine
    privileged: true
    pid: "host"
    working_dir: /app
    volumes:
      - .:/app
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/hostfs:ro
    environment:
      - DATABASE_URL=postgres://pulsar_user:pulsar_password@postgres:5432/pulsar_db?sslmode=disable
      - REDIS_ADDR=redis:6379
      - HOST_PROC=/host/proc
      - HOST_SYS=/host/sys
      - HOST_ETC=/host/etc
      - ROOT_FS=/hostfs
    command: sh -c "go mod download && go run cmd/api/main.go"
    ports:
      - "8081:8080"
    networks:
      - pulsar_net
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  worker:
    container_name: pulsar_worker
    image: golang:1.24-alpine
    working_dir: /app
    privileged: true
    pid: "host"
    volumes:
      - .:/app
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/hostfs:ro
    environment:
      - DATABASE_URL=postgres://pulsar_user:pulsar_password@postgres:5432/pulsar_db?sslmode=disable
      - REDIS_ADDR=redis:6379
      - HOST_PROC=/host/proc
      - HOST_SYS=/host/sys
      - HOST_ETC=/host/etc
      - ROOT_FS=/hostfs
    # -------------------------
    command: sh -c "go mod download && go run cmd/worker/main.go"
    networks:
      - pulsar_net
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  frontend:
    container_name: pulsar_frontend
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./web:/app
    environment:
      - VITE_API_URL=http://localhost:8081
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "3001:5173"
    networks:
      - pulsar_net
    depends_on:
      - backend

volumes:
  postgres_data:
  redis_data:

networks:
  pulsar_net:
    driver: bridge
